Soundrise/Soundrise/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('content/home/', permanent=True)),
    path('content/', include('content.urls')),
    path('beats/', include('beats.urls')),
    path('beatmakers/', include('beatmakers.urls')),
    path('accounts/', include('accounts.urls')),
]

#urls.py
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Soundrise/accounts/urls.py
from django.conf import settings
from django.urls import path , include
from . import views
from django.conf.urls.static import static 




app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('toggle_follow/<int:user_id>/<int:beat_id>/', views.toggle_follow, name='toggle_follow'),
    path('success/', views.success, name='success'),
    path('parametre/', views.parametre, name='parametre'),
    path('recherhche/', views.recherche, name='recherhce'),
    path('parametre/page/<str:page>/', views.parametre_onglet, name='parametre_onglet'),
    path('explore/',views.explore,name='explore'),
    path('search_beatmakers/',views.search_beatmakers,name='search_beatmakers'),
    path('detail_beat/<int:beat_id>/', views.detail_beat, name='detail_beat'),
    path('parametre/default',views.parametre_default,name='parametre_default'),
    path('create_card/',views.create_card,name='create_card'),
    path('create_paypal/',views.create_paypal,name='create_paypal'),
    path('parametre/activite-beat', views.parametre_like, name='parametre_like'),
    path('parametre/activite-fav', views.parametre_fav, name='parametre_fav'),
    path('parametre/activite-com', views.parametre_com, name='parametre_com'),
    path('parametre/historique-beat', views.historique_beat, name='historique_beat'),
    path('parametre/historique-artist', views.historique_artist, name='historique_artist'),
    path('parametre/historique-recherche', views.historique_recherche, name='historique_recherche'),
    path('parametre/transaction',views.parametre_transaction,name="parametre_transaction"),
    path('conversations', views.get_conversations, name='conversations'),
    path('conversation/<int:conversation_id>', views.get_messages, name='get_messages'),
    path('add_conversation/<int:participant1_id><int:participant2_id>', views.add_conversation, name='add_conversation'),
    path('create_conversation/<int:participant1_id><int:participant2_id>', views.create_conversation, name='create_conversation'),
    path('create_message', views.create_message, name='create_message'),
    path('pulse',views.pulse,name='pulse'),
    path('playlist/<int:id>/lire/', views.lire_titre, name='lire_titre'),
    path('playlist/<int:id>/supprimer/', views.supprimer_titre, name='supprimer_titre'),
    path('ajouter_titre/', views.topbar, name='ajouter_titre'),
    
    

    
    

    
]

Soundrise/beats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'beats'

urlpatterns = [
    path('upload/', views.upload_beat, name='upload_beat'),
    path('update_views/', views.update_views, name='update_views'),
]

Soundrise/files/templates/pages/parametre/abonnement.html
{% extends 'pages/parametre.html' %}

{% block content2 %}
<div class = "onglet-parametre-default">    
    <div class="me">
        <div class="actuel">
            <div class="actuel2">Abonnement actuel
            <div class="corp">Abonnement Premium
                <div class="data1">mois d'abonnement consécutif :
                    <div class="variable1">3</div>
                </div>
                <div class="data1">Abonné depuis le :
                    <div class="variable">12 janvier 2024</div>
                </div>
                <div class="prix">19,99$/mois</div>
            </div>
            </div>
        </div>
        <div class="border1"></div>
        
        <div class="paiement">
        <div class="paiement2">Infos paiement
          <div class="titre-abo">  
            <div class="name">
                    <div>Francois</div>
                    <div>Philippe</div>
                </div>
                <div class="cb1">Mastercard
                    <div>
                        <div class="perso-abo">CVC</div>
                        <div class="private">**** **** **** 2345</div>
                    </div>
                    <div>
                        <div class="perso-">Code</div>
                        <div class="private">****</div>
                    </div>
                </div>
            </div>  
        </div>
        </div>
    </div>
    
    <div class="abonnement1">
        <div class="card1">
            <span class="title1"
              >Standard
              <p class="pricing">$4.99 <span class="pricing-time">/ month</span></p>
              <span class="sub-title"
                >Everything on Basic plus:
                <ul class="list1">
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                </ul>
                <button class="button1">
                  <span class="text-button1">Get Standard now</span>
                </button>
              </span></span
            >
          </div>
          
          <div class="card1">
            <span class="title1"
              >Pro
              <p class="pricing">$9.99 <span class="pricing-time">/ month</span></p>
              <span class="sub-title"
                >Everything on Basic plus:
                <ul class="list1">
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                </ul>
                <button class="button1">
                  <span class="text-button1">Get pro now</span>
                </button>
              </span></span
            >
          </div>
          <div class="card1">
            <span class="title1"
              >Premium
              <p class="pricing">$29.99 <span class="pricing-time">/ month</span></p>
              <span class="sub-title"
                >Everything on Basic plus:
                <ul class="list1">
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                  <li class="list-item"><span class="check">✓</span> Feature</li>
                </ul>
                <button class="button1">
                  <span class="text-button1">Get premium now</span>
                </button>
              </span></span
            >
          </div>


    
    </div>
</div>
{% endblock content2 %}

Soundrise/files/templates/pages/parametre/about.html
{% extends 'pages/parametre.html' %}

{% block content2 %}
<h1>Soundrise : Achetez, vendez et promouvez vos beats</h1>

    <h2>Présentation</h2>

    <p>Soundrise est une plateforme innovante dédiée aux beatmakers et aux artistes de musique. Elle offre une solution complète pour acheter, vendre et promouvoir des beats de haute qualité.</p>

    <h2>Fonctionnalités principales</h2>

    <h3>Acheter des beats</h3>

    <p>Sur Soundrise, vous trouverez une vaste collection de beats dans tous les styles imaginables. Vous pouvez parcourir les beats par genre, par humeur, par instrumentiste et par bien d'autres critères. Une fois que vous avez trouvé un beat qui vous plaît, vous pouvez l'acheter en toute sécurité et le télécharger instantanément.</p>

    <h3>Vendre des beats</h3>

    <p>Si vous êtes un beatmaker, Soundrise vous permet de vendre vos beats à un public mondial. Vous pouvez créer votre propre boutique en ligne et définir vos propres prix. Vous aurez également accès à des outils marketing pour promouvoir vos beats et toucher un plus large public.</p>

    <h3>Promouvoir vos beats</h3>

    <p>Soundrise propose plusieurs options pour promouvoir vos beats. Vous pouvez par exemple publier des pulses dans lesquelles vous faites la promotion de votre dernier beat </p>

    <h2>Avantages de Soundrise</h2>

    <p>Soundrise offre de nombreux avantages aux beatmakers et aux artistes de musique, notamment :</p>

    <ul>
        <li>Une vaste collection de beats de haute qualité</li>
        <li>une plateforme sécurisée et facile à utiliser</li>
        <li>Des outils marketing puissants pour promouvoir vos beats</li>
        <li>Une communauté active de beatmakers et d'artistes</li>
        <li>Un support client réactif</li>
    </ul>

    <h2>Commencez dès aujourd'hui !</h2>

    <p>Si vous êtes prêt à acheter, vendre ou promouvoir vos beats, inscrivez-vous dès aujourd'hui à Soundrise. C'est gratuit et facile !</p>

    <a href="{% url 'accounts:register'%}" class="btn">Inscription gratuite</a>

    <h2>FAQ</h2>

    <h3>Qu'est-ce qu'un beat ?</h3>

    <p>Un beat est une base instrumentale sur laquelle les artistes peuvent rapper ou chanter. Les beats sont généralement créés à l'aide de logiciels de production musicale ou de samplers.</p>

    <h3>Quels sont les différents types de beats ?</h3>

    <p>Il existe de nombreux types de beats différents, notamment les beats hip-hop, les beats pop, les beats EDM, les beats R&B et les beats jazz.</p>

    <h3>Comment puis-je acheter un beat sur Soundrise ?</h3>

    <p>Pour acheter un beat sur Soundrise, vous devez d'abord créer un compte. Une fois que vous avez créé un compte, vous pouvez parcourir les beats et les acheter en toute sécurité avec votre carte de crédit ou votre compte PayPal.</p>

    <h3>Comment puis-je vendre des beats sur Soundrise ?</h3>

    <p>Pour vendre des beats sur Soundrise, vous devez d'abord créer un compte. Une fois connecté , vous pouvez télécharger vos beats et les mettre en vente dans la page sell.</p>

    <h3>Comment puis-je promouvoir mes beats sur Soundrise ?</h3>

    <p>Soundrise propose les pulses , le meilleur moyen de promouvoir son contenu .Créer la nouvelle trend</p>
{% endblock content2 %}

Soundrise/files/templates/pages/parametre/aide.html
{% extends 'pages/parametre.html' %}

{% block content2 %}
<div class = "onglet-parametre-default">
    <div class=onglet-int >
        <div class="partie">
            <div class="titre2-aid">Question fréquentes</div>
            <div class="box-aid">
                <div class="question-aid" >Comment puis-je vendre mes beats sur Soundrise ?</div>
                <div class="question-aid">Comment puis-je acheter des beats sur BeatStars ?</div>
                <div class="question-aid">Comment puis-je contacter l'assistance ?</div>
                <div class="question-aid">Que faire si je ne suis pas satisfait d'un beat que j'ai acheté ?</div>
                <div class="question-aid">Comment puis-je promouvoir mes beats ?</div>
                <div class="question-aid">Comment puis-je protéger mes droits d'auteur sur mes beats ?</div>
                <div class="question-aid">Comment puis-je utiliser les beats que j'achète ?</div>
                <div class="question-aid">Comment puis-je personnaliser mon profil ?</div>
                <div class="question-aid">Comment puis-je promouvoir ma musique ?</div>
                <div class="question-aid">Comment personnaliser son profil ?</div>
                <div class="question-aid">Quels sont les futures fonctionnalités ?</div>
                <div class="question-aid">Comment ne pas se faire piégé ?</div>

            </div>
        </div>
        <div class="partie">
            
                <div class="titre-aid">Contact</div>
                <div class="box2-aid">
                    <h6 class="aligner-titre" >Adresse mail  : Soundrise@gmail.com</h6>
                    <div class="titre2-aid">Contacter nous :</div>
                    <button class="contact" >Contact</button>

                </div>
                <div class="titre3-aid">Avis
                <div class="box2-aid">
                    
                    <input  type = " text" class="avis" placeholder="Que pensez vous de soundrise ?"></input>
                    <button class="send">Send</button>
                    <div class="rating">
                        <input value="5" name="rate" id="star5" type="radio">
                        <label title="text" for="star5"></label>
                        <input value="4" name="rate" id="star4" type="radio">
                        <label title="text" for="star4"></label>
                        <input value="3" name="rate" id="star3" type="radio" checked="">
                        <label title="text" for="star3"></label>
                        <input value="2" name="rate" id="star2" type="radio">
                        <label title="text" for="star2"></label>
                        <input value="1" name="rate" id="star1" type="radio">
                        <label title="text" for="star1"></label>
                    </div>

                </div>
        </div>
    </div>
</div>
    
    
                
    
                
        

    
    
    </div>
    <style>
        @media screen and (max-width:790px) {
            .aligner-titre{
                align-items: center;
                margin-left: 20%;
            }
            .avis{
                width: 80%;
                height: 80px;
               
            }
        }
    </style>
{% endblock content2 %}

Soundrise/files/templates/pages/parametre/historique-beat.html
{% extends 'pages/parametre.html' %}

{% block content2 %}
<div class = "onglet-parametre-default">
    <div class="recherche-act">
        <div class="nothing"></div>
        <div class="nothing"></div>
        <button class="but-act"  ><a href="{% url 'accounts:historique_beat'%}" style="color : white">Beat</a></button>
        <button class="but-act" ><a href="{% url 'accounts:historique_artist'%}" style="color : white">Artist</a></button>
        <button class="but-act" ><a href="{% url 'accounts:historique_recherche'%}" style="color : white">research</a></button>
        <div class="nothing"></div>
        <div class="nothing"></div>
    </div>
    
</div>
{% endblock content2 %}

Soundrise/files/templates/pages/parametre/historique-recherche.html
{% extends 'pages/parametre.html' %}

{% block content2 %}
<div class = "onglet-parametre-default">
    <div class="recherche-act">
        <div class="nothing"></div>
        <div class="nothing"></div>
        <button class="but-act"  ><a href="{% url 'accounts:historique_beat'%}" style="color : white">Beat</a></button>
        <button class="but-act" ><a href="{% url 'accounts:historique_artist'%}" style="color : white">Artist</a></button>
        <button class="but-act" ><a href="{% url 'accounts:historique_recherche'%}" style="color : white">research</a></button>
        <div class="nothing"></div>
        <div class="nothing"></div>
    </div>
    <div class="box-rec">
        <div class="division-rec"></div>
        <div class="contenu-rec">
            <div class="catégorie-rec">
                <div class="subject1-rec">Recherche</div>
                <div class="date1-rec">Date</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Beat</div>
                <div class="date-rec">19/06</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Song</div>
                <div class="date-rec">19/06</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Song cool</div>
                <div class="date-rec">19/07</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Beat rapide</div>
                <div class="date-rec">19/07</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">hit</div>
                <div class="date-rec">19/07</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">beat été</div>
                <div class="date-rec">19/08</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">instru rap</div>
                <div class="date-rec">19/08</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">hit été</div>
                <div class="date-rec">19/09</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Maddy pain</div>
                <div class="date-rec">19/09</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Desbois</div>
                <div class="date-rec">19/09</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Beat</div>
                <div class="date-rec">1909</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">beat long</div>
                <div class="date-rec">19/10</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">110 bpm</div>
                <div class="date-rec">19/10</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">beat pas cher</div>
                <div class="date-rec">19/10</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">song remix</div>
                <div class="date-rec">19/11</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">remix beat luis</div>
                <div class="date-rec">19/11</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">David guetto</div>
                <div class="date-rec">19/11</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">maitre gimnastique</div>
                <div class="date-rec">19/12</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Johny allydays</div>
                <div class="date-rec">19/12</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Robin caillou</div>
                <div class="date-rec">19/12</div>
            </div>

            <div class="ligne-rec">
                <div class="subject-rec">The week</div>
                <div class="date-rec">19/01</div>
            </div>
            <div class="ligne-rec">
                <div class="subject-rec">Jean jacques geul man</div>
                <div class="date-rec">19/01</div>
            </div>
            
        </div>
        <div class="division-rec"></div>
    </div>
</div>
{% endblock content2 %}

Soundrise/files/templates/pages/parametre/tableau.html
{% extends 'pages/parametre.html' %}
{% block content2 %}

<div class = "onglet-parametre-default">
    <div class="revenus">
        <div class="graph">
            <div class="graph2"  >
        

            <div class="ligne-tab">
                <div class="t">Revenus($)</div>
                
            </div>
            <div class="ligne-tab">
                <div class="chiffre">100k</div>
                <div class="l"></div>
            </div>
            <div class="ligne-tab">
                <div class="chiffre">10k</div>
                <div class="l"></div>
            </div>
            <div class="ligne-tab">
                <div class="chiffre">1k</div>
                <div class="l"></div>
            </div>
            <div class="ligne-tab">
                <div class="chiffre">100</div>
                <div class="l"></div>
            </div>
            <div class="ligne-tab">
                <div class="chiffre">10</div>
                <div class="l"></div>
            </div>
            <div class="ligne2-tab">
                <div class="chiffre2">0</div>
                <div class="l2">1</div>
                <div class="l2">2</div>
                <div class="l2">3</div>
                <div class="l2">4</div>
                <div class="l2">5</div>
                <div class="l2">10</div>
                <div class="l2">20</div>
                <div class="l2">30</div>
                <div class="t2">Semaine(s+)</div>
                    
            </div>
            </div>
            
        </div>

        <div class ="donnees">
            <div class="donnees2" >
            <div class="donnees3">Latest Beat
            <div class="j2">
                <div class="j">
                <div class="analy">Ecoutes</div>
                <div class="data-tab">{{latest_model.title}}</div>
            
            </div>  
            <div class="j">
                <div class="analy">Ventes</div>
                <div class="data-tab" >600</div>
                
                
            </div>
            <div class="j">
                <div class="analy">Revenus</div>
                <div class="data-tab">3.4k</div>
                
                
            </div>
            </div>
            
            <div >
                <div ></div>
                <div ></div>
            </div>
            </div>
            </div>
        </div>
    </div>
    
    <div class = "stats">
        
        <div class="stat1">
            <div class="stat2-1">Ecoutes
                
            <div class="nombre">{{user_account.like_numbers}}</div>
            <div class="info-tab">en hausse de %</div>
            </div>
        </div>
        <div class="stat1">
            <div class="stat2-2" >Abonnés
            <div class="nombre">{{ user_account.follower_count }}</div>
            <div class="info-tab">en hausse de %</div>
            </div>
        </div>
        <div class="stat1">
            <div class="stat2-3">Moyenne
                <div class="moyennes">
                <div class="typ">Ecoutes</div>
                <div class="num">103k</div>
                </div>
            
            <div class="moyennes">
                <div class="typ">Ventes</div>
                <div class="num">1.6k</div>
            </div>
            <div class="moyennes">
                <div class="typ" >revenus</div>
                <div class="num">20.76k</div> 
            </div>
            </div>
        </div> 
        
    </div>
    
    <div class="liste-tab">
        <div class="liste2-tab">
        <div class="categorie-tab">
            <div class="infos-tab">Beat</div>
            <div class="infos-tab">Title</div>
            <div class="infos-tab">Likes</div>
            <div class="infos-tab">Price</div>
            <div></div>
        </div>
        <div class="beatinfos">
            
                {% if uploaded_beats %}
                    {%for beat in uploaded_beats%}
                    <div class="li-tab">
                    <img class="inf1" src="{{beat.cover_image.url}}"></img>
                    <h6 class ='inf2'>{{beat.title}}</h6> 
                    <div class="inf2">
                        
                     
                            
                            <svg fill="white" viewBox="0 0 512 512" height="1em" xmlns="http://www.w3.org/2000/svg"><path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"></path></svg>
                            <h6 class ='inf2'>10k</h6>
                            
                        
                    </div>
                    <div class="inf3">{{beat.price}}€</div>
                    </div>
                    {% endfor %}
                {% else %}
                <p class="text-muted">No beats uploaded yet.</p>
                <a href="{% url 'beats:upload_beat' %}">upload</a>
                {% endif %}

            

        
            </div>
        </div>
    </div>
</div>
<style>
    @media screen and (min-width:990px) and (max-width:1170px) {
  
        .data-tab{
            font-size: 20px;
           width: 10%;
           margin-left: -50%;
           margin-top: 10%;
        }
        .analy{
            font-size: 20px;
            margin-left: -10%;
        }
        .typ{
            font-size: 15px;
            margin-top: 10%;
        }
        .num{
            font-size: 15px;
            margin-top: 10%;
        }
        .inf1{
            width: 8%;
            margin-left: 25px;
        }
  }
  

  @media screen and (min-width:701px) and (max-width:989px) {
  
  .revenus{
    display: flex;
    flex-direction: column;
    height: 100%;
  }
  .graph{
    width: 80%;
    align-self: center;
  }
  
  .typ{
      font-size: 15px;
      margin-top: 10%;
  }
  .num{
      font-size: 15px;
      margin-top: 10%;
  }
  .j{
    justify-content: left ;
    display: flex;
    flex-direction: column;
    
  }
  .j2{
    display: flex;
    flex-direction: row;
  }
  .donnees{
    width: 80%;
    align-self: center;
    margin-left: 2%;
    height: 40%;
    
  }
  .donnees2{
    width: 101%;
    margin-left: -0.5%;
  }
  .donnees3{
    width: 100%;
  }
  .stat1{
    width: 27%;
  }
  .liste-tab{
   width: 80%;
   margin-left: 10%;
    
    
  }
  .liste2-tab{
    margin-left: -0.5%;
    width: 101%;
  }
  .inf1{
            width: 15%;
            margin-left: 55px;
        }
}

@media screen and (min-width:576px) and (max-width:700px) {
  
  .revenus{
    display: flex;
    flex-direction: column;
    height: 100%;
  }
  .graph{
    width: 80%;
    height: 40%;
    align-self: center;
  }
  .chiffre{
    margin-top: -2%;
  }
  .ligne2-tab{
    width: 80%;
  }
  .typ{
      font-size: 10px;
      margin-top: 15%;
  }
  .num{
      font-size: 10px;
      margin-top: 15%;
  }
  .j{
    justify-content: left ;
    display: flex;
    flex-direction: column;
    
  }
  .j2{
    display: flex;
    flex-direction: row;
  }
  .donnees{
    width: 80%;
    align-self: center;
    margin-left: 2%;
    height: 30%;
    
  }
  .donnees2{
    width: 101%;
    margin-left: -0.5%;
  }
  .donnees3{
    width: 100%;
  }
  .stats{
    flex-direction: row;
    height: 35%;
    width: 25%;
    margin-left: 38%;
    
  }
  
  .stat1{
    width: 100%;
  }
  .liste-tab{
   width: 80%;
   margin-left: 10%;
    
    
  }
  .liste2-tab{
    margin-left: -0.5%;
    width: 101%;
  }
  .analy{
    font-size: 15px;
  }
  .data-tab{
    font-size: 15px;
    margin-left: -20px;
  }
  .info-tab{
    font-size: 7px;
    margin-top:60px;
    white-space: nowrap;
  }
  .inf1{
            width: 20%;
            margin-left: 55px;
        }
    

}


@media screen  and (max-width:575px) {
  
  .revenus{
    display: flex;
    flex-direction: column;
    height: 100%;
  }
  .graph{
    width: 80%;
    height: 30%;
    align-self: center;
    margin-bottom: 0%;
  }
  .chiffre{
    margin-top: -2%;
    margin-right: 10px;
  }
  .ligne2-tab{
    width: 80%;
  }
  .typ{
      font-size: 15px;
      margin-top: 10%;
  }
  .num{
      font-size: 15px;
      margin-top: 10%;
  }
  .j{
    justify-content: left ;
    display: flex;
    flex-direction: column;
    
  }
  .j2{
    display: flex;
    flex-direction: row;
  }
  .donnees{
    width: 80%;
    align-self: center;
    margin-left: 2%;
    height: 30%;
    margin-bottom: 0%;
    margin-top: 0%;
    
  }
  .donnees2{
    width: 101%;
    margin-left: -0.5%;
  }
  .donnees3{
    width: 100%;
  }
  .stats{
    flex-direction: column;
    height: 150%;
    width: 50%;
    margin-left: 25%;
    
  }
  .li-tab{
    width: 100%;
   
  }
  .inf3{
    margin-right: 50px;
  }
  .inf2{
    font-size: 10px;
  }
  .categorie-tab{
    padding-left: 20px;
  }
  .stat1{
    width: 100%;
  }
  .liste-tab{
   width: 80%;
   margin-left: 10%;
    
    
  }
  .liste2-tab{
    margin-left: -0.5%;
    width: 101%;
  }
  .analy{
    font-size: 15px;
    margin-left: 5%;
  }
  .data-tab{
    font-size: 15px;
    margin-left: -20px;
  }
  .info-tab{
    font-size: 7px;
    margin-top:60px;
    white-space: nowrap;
  }
  .inf1{
            width: 25%;
            margin-left: -15px;
        }  
  .t{
    margin-top: -10px;
  } 
}








</style>
{% endblock content2 %}