Soundrise/Soundrise/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('content/home/', permanent=True)),
    path('content/', include('content.urls')),
    path('beats/', include('beats.urls')),
    path('beatmakers/', include('beatmakers.urls')),
    path('accounts/', include('accounts.urls')),
]

#urls.py
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Soundrise/accounts/urls.py
from django.conf import settings
from django.urls import path , include
from . import views
from django.conf.urls.static import static 




app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('toggle_follow/<int:user_id>/<int:beat_id>/', views.toggle_follow, name='toggle_follow'),
    path('success/', views.success, name='success'),
    path('parametre/', views.parametre, name='parametre'),
    path('recherhche/', views.recherche, name='recherhce'),
    path('parametre/page/<str:page>/', views.parametre_onglet, name='parametre_onglet'),
    path('explore/',views.explore,name='explore'),
    path('search_beatmakers/',views.search_beatmakers,name='search_beatmakers'),
    path('detail_beat/<int:beat_id>/', views.detail_beat, name='detail_beat'),
    path('parametre/default',views.parametre_default,name='parametre_default'),
    path('create_card/',views.create_card,name='create_card'),
    path('create_paypal/',views.create_paypal,name='create_paypal'),
    path('parametre/activite-beat', views.parametre_like, name='parametre_like'),
    path('parametre/activite-fav', views.parametre_fav, name='parametre_fav'),
    path('parametre/activite-com', views.parametre_com, name='parametre_com'),
    path('parametre/historique-beat', views.historique_beat, name='historique_beat'),
    path('parametre/historique-artist', views.historique_artist, name='historique_artist'),
    path('parametre/historique-recherche', views.historique_recherche, name='historique_recherche'),
    path('parametre/transaction',views.parametre_transaction,name="parametre_transaction"),
    path('conversations', views.get_conversations, name='conversations'),
    path('conversation/<int:conversation_id>', views.get_messages, name='get_messages'),
    path('add_conversation/<int:participant1_id><int:participant2_id>', views.add_conversation, name='add_conversation'),
    path('create_conversation/<int:participant1_id><int:participant2_id>', views.create_conversation, name='create_conversation'),
    path('create_message', views.create_message, name='create_message'),
    path('pulse',views.pulse,name='pulse'),
    path('playlist/<int:id>/lire/', views.lire_titre, name='lire_titre'),
    path('playlist/<int:id>/supprimer/', views.supprimer_titre, name='supprimer_titre'),
    path('ajouter_titre/', views.topbar, name='ajouter_titre'),
    
    

    
    

    
]

Soundrise/beats/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'beats'

urlpatterns = [
    path('upload/', views.upload_beat, name='upload_beat'),
    path('update_views/', views.update_views, name='update_views'),
]

Soundrise/content/urls.py
from django.urls import path
from . import views

app_name = 'content'


urlpatterns = [
    path('home/', views.index, name='index'),
]

Soundrise/files/templates/blocks/bottombar.html
{% block bottombar %}
<nav class="navbar fixed-bottom" style="background-color: rgb(29, 29, 29); border-top: 1px solid #464646; padding: 5px 0; max-height: 37px;">
  <div class="bottom d-flex justify-content-around align-items-center w-100 " style=" margin-left: 20px; " >
      <div class="text-center">
          <a href="{% url 'accounts:parametre_onglet' 'default' %}" class="nav-item nav-link d-inline-block" style="font-size: 70%; ">Parametre</a>
          <a href="{% url 'accounts:parametre_onglet' 'about' %}" class="nav-item nav-link d-inline-block" style="font-size: 70%;">About</a>
          <a href="{% url 'accounts:parametre_onglet' 'confidentiality' %}" class="nav-item nav-link d-inline-block" style="font-size: 70%;">Confidentiality</a>
          <a href="{% url 'accounts:parametre_onglet' 'cookie' %}" class="nav-item nav-link d-inline-block" style="font-size: 70%;">Cookie</a>
      </div>
      <!----à finir       code ;    <div class="play" {% if current_beat %} style="display: flex;" {% else %}  {% endif %} >
        <div class="buttons">
          <button class="skip-btn"><svg viewBox="0 0 16 16" class="bi bi-skip-backward-fill" fill="currentColor" height="16" width="16" xmlns="http://www.w3.org/2000/svg"> <path d="M.5 3.5A.5.5 0 0 0 0 4v8a.5.5 0 0 0 1 0V8.753l6.267 3.636c.54.313 1.233-.066 1.233-.697v-2.94l6.267 3.636c.54.314 1.233-.065 1.233-.696V4.308c0-.63-.693-1.01-1.233-.696L8.5 7.248v-2.94c0-.63-.692-1.01-1.233-.696L1 7.248V4a.5.5 0 0 0-.5-.5z"></path> </svg></button>
        </div>
        <audio id="audio-player" controls {% if current_beat %} autoplay {% endif %}>
          <source src="{{ current_beat.audio_file_url }}" type="audio/mp3">
          Your browser does not support the audio element.
        </audio>
        <progress id="progress_{{ current_beat.id }}" value="{{ audio_player_state.currentTime }}" max="{{ audio_player_state.duration }}" style="opacity: 0%;"></progress>
        <div class="buttons">
            
            <button class="skip-btn"><svg viewBox="0 0 16 16" class="bi bi-skip-backward-fill" fill="currentColor" height="16" width="16" xmlns="http://www.w3.org/2000/svg"> <path d="M.5 3.5A.5.5 0 0 0 0 4v8a.5.5 0 0 0 1 0V8.753l6.267 3.636c.54.313 1.233-.066 1.233-.697v-2.94l6.267 3.636c.54.314 1.233-.065 1.233-.696V4.308c0-.63-.693-1.01-1.233-.696L8.5 7.248v-2.94c0-.63-.692-1.01-1.233-.696L1 7.248V4a.5.5 0 0 0-.5-.5z"></path> </svg></button>
            
           
          </div>
          </div>
              -->
     
      

        
      

      <div class="text-center">
          <p class="m-0" style="font-size: 12px;">Soundrise copyright © all rights reserved</p>
      </div>
  </div>
</nav>
<style>
    
    .play{
        width:30% ;
        height: 30px;
        border-style: groove;
        border-color: #ffffff;
        display: flex;
        flex-direction: row;
        justify-content: center;
    }
    .m-0{
        white-space: nowrap;
    }
    

    
</style>
<script>



  
  function togglePlayPause(beatId) {
        var audio = document.getElementById('audio_' + beatId);
        var playIcon = document.getElementById('play_icon_' + beatId);
        var pauseIcon = document.getElementById('pause_icon_' + beatId);
        var allAudios = document.querySelectorAll('audio');
    
        // Pause all other audios
        allAudios.forEach(function(aud) {
            if (aud.id !== 'audio_' + beatId) {
                aud.pause();
                var otherBeatId = aud.id.split('_')[1];
                var otherPlayIcon = document.getElementById('play_icon_' + otherBeatId);
                var otherPauseIcon = document.getElementById('pause_icon_' + otherBeatId);
                otherPlayIcon.style.display = 'inline-block';
                otherPauseIcon.style.display = 'none';
            }
        });
    
        // Toggle play/pause for the selected beat
        if (audio.paused) {
            audio.play();
            playIcon.style.display = 'none';
            pauseIcon.style.display = 'inline-block';
        } else {
            audio.pause();
            playIcon.style.display = 'inline-block';
            pauseIcon.style.display = 'none';
        }
            // Ajax call to update views
      var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      var xhr = new XMLHttpRequest();
      xhr.open('POST', '{% url "beats:update_views" %}', true);
      xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
      xhr.setRequestHeader('X-CSRFToken', csrftoken);
      xhr.onreadystatechange = function() {
          if (xhr.readyState === 4 && xhr.status === 200) {
              var response = JSON.parse(xhr.responseText);
              if (response.success) {
                  console.log('Views updated successfully:', response.views);
              } else {
                  console.error('Failed to update views:', response.error);
              }
          }
      };
      xhr.send('beat_id=' + beatId);
  
    }
    function updateViews(beatId) {
  
            // Ajax call to update views
      var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      var xhr = new XMLHttpRequest();
      xhr.open('POST', '{% url "beats:update_views" %}', true);
      xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
      xhr.setRequestHeader('X-CSRFToken', csrftoken);
      xhr.onreadystatechange = function() {
          if (xhr.readyState === 4 && xhr.status === 200) {
              var response = JSON.parse(xhr.responseText);
              if (response.success) {
                  console.log('Views updated successfully:', response.views);
              } else {
                  console.error('Failed to update views:', response.error);
              }
          }
      };
      xhr.send('beat_id=' + beatId);
  
    }
    function seekAudio(beatId) {
        var audio = document.getElementById('audio_' + beatId);
        var seekbar = document.getElementById('seekbar_' + beatId);
        var value = seekbar.value;
        audio.currentTime = value;
    }
    
    function updateProgressBar(beatId) {
        var audio = document.getElementById('audio_' + beatId);
        var progressBar = document.getElementById('progress_' + beatId);
        var seekbar = document.getElementById('seekbar_' + beatId);
    
        var value = (audio.currentTime / audio.duration) * 100;
        progressBar.value = value;
        seekbar.value = audio.currentTime;
    
        updateSeekbarTooltip(seekbar);
    }
    
    function updateSeekbarTooltip(seekbar) {
        var tooltip = seekbar.nextElementSibling;
        var value = seekbar.value;
        var minutes = Math.floor(value / 60);
        var seconds = Math.floor(value % 60);
        var time = minutes + ':' + (seconds < 10 ? '0' : '') + seconds;
        tooltip.innerHTML = time;
        tooltip.style.left = (value / seekbar.max) * 100 + '%';
    }
  
  
  </script>
{% endblock bottombar %}

Soundrise/files/templates/blocks/side.html
{% block side %}

<div class="side-bar" style="color: transparent;display:flex ; flex-direction: row; justify-content:  center;">
    <a href="{% url 'accounts:pulse'%}" style="align-self: center;"><i class="fa-regular fa-circle-play fa-xl" style="color: #ffffff; "></i></a>

</div>


<style>
    .side-bar{
        height: 610px;
        width: 100px;
        align-self: left;
        background-color: rgba(29, 29, 29, 0.7);
        
    }
</style>
{% endblock side %}

Soundrise/files/templates/blocks/topbar.html
{% block topbar %}
    <nav class="navbar" style="background-color: rgb(29, 29, 29); border-bottom: 1px solid #464646; ">
        <div id="left">

        </div>

        
        <div id="center">

            <a href="{% url 'content:index' %}" id='logo_home' class="navbar-top-item"><strong>Soundrise</strong></a>
            
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:explore' %}" class="navbar-top-item">Explore</a>
                <div class="form">
                    <form action="{% url 'accounts:explore' %}" method="GET" class="form2">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" id="search" name="search" class="form-control me-2" placeholder="Search... ">
                            <button type="submit" class="theBut" >Search</button>
                        </div>
                    </form>
                    
                </div>

                
            {% else %}
                <a href="{% url 'accounts:explore' %}" class="navbar-top-item">Explore</a>
                <div class="form">
                    <form method="GET" class="form2">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" id="search" name="search" class="form-control me-2" placeholder="Search..." value="{{ search_term }}" >
                            <button type="submit" class="theBut" >Search</button>
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>

        <div id="right">
            {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}" class="navbar-top-item"  >Profile</a>
            <a href="{% url 'accounts:logout' %}" class="navbar-top-item"  >Logout</a>
            {% else %}
            <a href="{% url 'accounts:login' %}" class="navbar-top-item"  >Login</a>
            <a href="{% url 'accounts:register' %}" class="navbar-top-item" >Register</a>
            {% endif %}
            {% if user.is_staff %}
            <a href="{% url 'admin:index' %}" class="navbar-top-item">Admin</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="{% url 'accounts:conversations' %}" class="navbar-top-item"  ><i class="fa-solid fa-message fa-lg" style="color: #ffffff;"></i></a>
            <button id="bouton-play"  class="navbar-top-item" style="background-color: transparent; border: none;" ><i class="fa-solid fa-compact-disc fa-lg" style="color: #ffffff;"></i></a>
                <div id="menu-play">
                    <ul style="display: flex;flex-direction: column;">
                        

                        
                        <ul>
                            
                            
                        </ul>
                        <div class="container-play">
                            <h4>Selection</h4>
                            <div class="liste-play">
                                {% for playlist_item in playlist %}
                                    <div class="ligne-play">
                                        <li>
                                            {{ playlist_item.beat.title }} -
                                            <a href="{% url 'lire_titre' playlist_item.beat.id %}">Lire</a> -
                                            <a href="{% url 'supprimer_titre' playlist_item.id %}" class="btn btn-danger">Supprimer</a>
                                        </li>
                                    </div>
                                {% endfor %}
                                
                            </div>
                            <div class="player">
                                <audio controls class="w-100">
                                    <source src="{{ beat.audio_file_url }}" type="audio/mp3">
                                    Your browser does not support the audio element.
                                </audio>
                                
                                
                                 
                            </div>
                    
                            <div class="playlist">
                                {% if titre_suivant %}
                                <a href="{% url 'lire_titre' titre_suivant %}">Lire suivant</a>
                                {% endif %}
                            </div>
                        </div>
                    </ul>
                    
                </div>
            {%endif%}
        </div>
    </nav>

<style>
    audio{
        display: flex;
    }
    .liste-play{
        height: 200px;
        width: 90%;
        margin-left: 5%;
        margin-bottom: 2%;
        
        overflow-y: scroll;
    }
    .ligne-play{
        height:100px;
        width: 100%;
        background-color: blue;
    }
    #menu-play {
    left: 1225px;
    top: 58px;
    display: flex;
    flex-direction: column;
    height: 300px;
    width: 300px;
    display: none;
    position: absolute;
    background-color: #3a3838;
    min-width: 200px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 2;
    border-radius: 10px;
}

#menu-play:hover #menu-play {
    display: block;
}

#menu-play ul {
    list-style: none;
    margin: 0;
    padding: 0;
}

#menu-play li {
    padding: 10px;
}
    .navbar-top-item{
        color: rgb(255, 255, 255); padding: 7px 0px;
    }
    .form-control-me-2{
        width: 300px;
    }
    #searchnone{
    display: none;
    }
    #search{
        border-radius: 50px;
        border: none;
        outline: none;
        width: 400px;
    }
    #center{
        display: flex;
    }
    .searchbtn
    {
        border-top-right-radius: 50px;
        border-bottom-right-radius: 50px;
        border: none;
        padding-right: 11px;
        position: absolute;
        top: 1px;
        left: 338px;
        padding: 6px 1px;
        background-color: #2d373f00;
        color: #fff;
    }
    .theBut{
        -webkit-border-top-right-radius: 5px;
        -webkit-border-bottom-right-radius: 5px;
        -moz-border-radius-topright: 5px;
       -moz-border-radius-bottomright: 5px;
         border-top-right-radius: 5px;
        background-color: dark;
        border-bottom-right-radius: 5px;
        color: white;
    }
    @media screen and (min-width:710px) and (max-width:950px){
        .input-group{
            flex-wrap: nowrap;
        width: 100%;
        }
       
        .w-100-d-flex{
            width: 10%;
        }
        .form{
            width: 60%;
            color: transparent;
        }
        .form2{
            width: 100%;
            
        }
        .theBut{
            background-color: transparent;
        }
        #center{
            width: 60%;
            box-sizing: none;
        }
    }   #left{
        width: 1%;
        justify-content: left;
    }

    @media screen and (min-width:651px) and (max-width:709px){
        .input-group{
            flex-wrap: nowrap;
        width: 100%;
        }
        .theBut{
            width: 15%;
            background-color: transparent;
        }
        .w-100-d-flex{
            width: 20%;
        }
        .form{
            width: 60%;
        }
        
        #center{
            width: 30%;
            box-sizing: none;
            margin-left: -100px;
        }
    }   #left{
        
        justify-content: left;
    }

    @media screen and (min-width:486px) and (max-width:650px){
        .input-group{
            flex-wrap: nowrap;
        width: 100%;
        }
        .theBut{
            width: 15%;
            background-color: transparent;
        }
        .w-100-d-flex{
            width: 20%;
        }
        .form{
            width: 60%;
        }
        #center{
            width: 30%;
            box-sizing: none;
            margin-left: -30%;
        }
          
        #left{
            
            justify-content: left;
        }
        .navbar-top-item{
            margin-left: 3px;
            margin-right: 3px;
        }
        } 
        @media screen and (min-width:0px) and (max-width:485px){
        .input-group{
            flex-wrap: nowrap;
        width: 100%;
        }
        .theBut{
            width: 15%;
            background-color: transparent;
            color: transparent;
            
        }
        .w-100-d-flex{
            width: 20%;
        }
        .form{
            width: 60%;
        }
        .form2{
            width: 130%;
        }
        #center{
            width: 30%;
            box-sizing: none;
            margin-left: -30%;
        }
          
        #left{
            
            justify-content: left;
        }
        .navbar-top-item{
            margin-left: 3px;
            margin-right: 3px;

            
        }
        
        } 


       
</style>
<script>
    const bouton = document.getElementById('bouton-play');
const menu = document.getElementById('menu-play');

bouton.addEventListener('click', () => {
    menu.style.display = menu.style.display === 'none' ? 'block' : 'none';
});





</script>
{% endblock topbar %}